language: node_js
node_js:
  - 8.9.4
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
script: gatsby build
deploy:
  provider: surge
  project: ./public/
  domain: wolfie-phy.surge.sh
  on: master
  skip_cleanup: true